import 'package:dio/dio.dart';

import '../model/post_api.dart';
import '../model/response_model.dart';

class PostRepository {
  Dio dio = Dio();

  Future<ResponseModel<List<Autogenerated>>> getPost() async {
    var response = await dio.get('https://jsonplaceholder.typicode.com/posts');
    List<Autogenerated> autogenerated = [];

try {
  for (var i in response.data) {
    autogenerated.add(Autogenerated.fromJson(i));
  }
return ResponseModel.complete(data: autogenerated);
}on DioError catch (e) {
  String message =
  e.response == null ? e.message : e.response!.data['detail'];
  if (e.type == DioErrorType.other) {
    return ResponseModel.withError(message: message);
  }
  return ResponseModel.withError(message: message);
} on Exception catch (e) {
  return ResponseModel.withError(message: e.toString());
}


  }
}
